### ISSUE TITLE
aimesh support

### ISSUE THREAD

**Issue by lu00** [RMerl/asuswrt-merlin.ng#114]
ac86u & more models aimesh support needed。

**Comment by RMerl** [comment]
At this time it's unlikely to be possible, due to technical limitations.

**Comment by vladut123** [comment]
Why aimesh is not supported

**Comment by RMerl** [comment]
As I said, it's unlikely to be possible due to technical reasons.  AiMesh code is closed source, and after a first glance at the implementation, it's likely to conflict with some of the changes I've done to the firmware.

More research would be required to determine if things can be worked around those incompatibilities, but right now this is a very low priority, especially since AiMesh itself is still very much a work-in-progress from Asus.
