### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by Stellarspace** [RMerl/asuswrt-merlin.ng#120]
Why doesn't it have an auto update feature?

**Comment by RMerl** [comment]
For many different reasons.  Reposted from a recent forum post:

---
First reason being Asus's routers (outside of the RT-AC86U) only have one single firmware partition. Flashing a firmware has to be done on top of a live firmware, which means high chances that the router will fail to reboot automatically, and require a manual power cycle. That makes any kind of automated firmware upgrade suicidal as it might leave your whole network down until you actually notice it. It also means a failed firmware update leaves your whole network down. If you don't have a valid firmware images to recover, then it'd be a nightmare to recover.

Second reason is it requires a secure authentication mechanism to protect against someone hijacking the process and pushing compromised firmware images to tens of thousands of routers. That means developing a firmware signing process that requires firmware images to be authenticated before being flashed. I refuse to accept the responsibility of this kind of risk.

Third reason is the infrastructure required, as I'd have to host the firmware images on my own server, with all the bandwidth, lots of time spent ensuring the security of the whole infrastructure and the server itself. Asuswrt-Merlin generates many hundreds of gigabytes of traffic per month in downloads, and a centralized download server becomes a target for hackers wishing to infect tens of thousands of devices just by compromising one single server.

Fourth is, I don't want my router to randomly cut a large download or online backup at 3 am because it just decided to update itself. I already despise Microsoft's decisions in that regard with Windows 10 (having corrupted my development VM not once, but twice - and one time it caused me to lose a whole evening of work).

So, never gonna happen with Asuswrt-Merlin for many reasons. When it comes to critical devices such as a router that is central to your whole network, any kind of automated firmware update is a really bad idea.
