### ISSUE TITLE
[OpenVPN] - parameter "duplicate-cn" always enabled

### ISSUE THREAD

**Issue by wlk** [RMerl/asuswrt-merlin.ng#192]
This the the configuration copied from `/etc/openvpn/server1/config.ovpn` (I logged to the router via ssh)

```
# Automatically generated configuration
daemon ovpn-server1
topology subnet
server 10.8.0.0 255.255.255.0
proto udp
port 1194
dev tun21
ncp-ciphers AES-128-GCM:AES-256-GCM:AES-128-CBC:AES-256-CBC
cipher AES-128-CBC
comp-lzo adaptive
keepalive 15 60
verb 3
push "route 192.168.16.0 255.255.255.0 vpn_gateway 500"
duplicate-cn
push "redirect-gateway def1"
ca ca.crt
dh dh.pem
cert server.crt
key server.key
status-version 2
status status 5

# Custom Configuration
```

Some of the configuration options are configurable via the Web-UI, but it's not possible to disable `duplicate-cn` parameter, preventing users from using various features like `ifconfig-pool-persist` because those 2 options are incompatible.

```
WARNING: --ifconfig-pool-persist will not work with --duplicate-cn
```

I suggest to add the option to disable `duplicate-cn` parameter via the Web-UI

**Comment by RMerl** [comment]
I don't want to dedicate a webui setting just for that parameter because it would be too esoteric (maybe 2 or 3 users would ever need that setting), and would go against the recent work done at simplifying it.

My recommendation for now is to create a postconf script that will remove that entry from the generated config file.
