### ISSUE TITLE
ip6tables version not support IPv6 NAT at kernel version 4.1.27

### ISSUE THREAD

**Issue by LiJinyao** [RMerl/asuswrt-merlin.ng#225]
My router is ASUS AC86U, linux kernel version info is
```
Linux RT-AC86U-D530 4.1.27 #2 SMP PREEMPT Sun Oct 21 14:26:37 EDT 2018 aarch64 ASUSWRT-Merlin
```
When I run `ip6tables -t nat -L`, I got the output said ipv6 nat is not supported
```
ip6tables v1.4.15: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
```
After google it, I found that  ip6tables support nat since `1.4.18`. But the install version is `1.4.15`. 

So dose the ip6tables should be upgraded?

PS.
_Why I need to do this is because I have a situation that I could only got one IPv6 address with prefix 128 by HDCPv6. And I also need IPv6 on my router so I could not just bridge IPv6 packet LAN to WAN. So I have to use NAT to let my LAN device have access to IPv6._

**Comment by yxmline** [comment]
ip6tables not support IPv6 NAT too bad

**Comment by samip5** [comment]
This would be beneficial to upgrade so when can use more advanced configurations.

**Comment by tenwx** [comment]
@LiJinyao 我用的是AC68U，之前一直以为只要换成AC86U后Kernel为4.1就能支持IPv6 NAT了，原来还是不支持呀

**Comment by noblehng** [comment]
The ipv6 netfilter nat kernel codes are not compiled in too.

After compile and load these:
```
CONFIG_NF_NAT_MASQUERADE_IPV6
CONFIG_IP6_NF_NAT
CONFIG_IP6_NF_TARGET_MASQUERADE
```
as kernel modules, nat66 works well.

But I still can't make policy routing for ipv6 work on ac86u, same settings works for normal linux machines though. Probably have something to do with broadcom's flowcache.

**Comment by MathewCNichols** [comment]
+1. It would be really nice to have ip6tables 1.4.18+ to use netfilter6:
http://tldp.org/HOWTO/Linux+IPv6-HOWTO/ch18s04.html 

Here is my situation, which works well on IPv4 with NAT, but cannot work with IPv6 enabled.

I use SSH, VPN, and host a web server behind my router. I use Merlin's inadyn to update my Google Domain A record. I point my SSH and VPN client config files to the same domain name. 

All goes well since SSH and VPN are served by the router, but I use the IPv4 port forwarding to forward ports 80 and 443 to the local web server.

Since an IPv6 AAAA record uses the web server's global IPv6 address, SSH and VPN will fail when using the domain name.

This would work if I could use the router's global IPv6 address, like I do with IPv4, and forward ports 80 and 443.

Thanks again to Eric and team for their continued work on this awesome software!
