### ISSUE TITLE
IP Wan invalid for HTTPS certificate

### ISSUE THREAD

**Issue by Comettii** [RMerl/asuswrt-merlin.ng#335]
Hi,

My IP WAN is ok...
![image](https://user-images.githubusercontent.com/53059569/61487036-4e39e780-a97b-11e9-9f98-dbdfef6681a7.png)

...but the Server Certificate shows my LOCAL IP like this:
![image](https://user-images.githubusercontent.com/53059569/61489755-ca372e00-a981-11e9-815e-f70910eba441.png)

Lookup its ok for DDNS:
![image](https://user-images.githubusercontent.com/53059569/61485957-bf2bd000-a978-11e9-8108-43e38985e837.png)

Any idea to resolve this?!

Thanks

**Comment by RMerl** [comment]
There is nothing to resolve.  The DDNS hostname is present in the SAN extension, which is the correct way to do this.  The WAN IP is not in the certificate because IPs are dynamic, and therefore can change at any time, which would require generating a new certificate every time.

This is working as intended.
