### ISSUE TITLE
Port Forwarding can not saved

### ISSUE THREAD

**Issue by panther7** [RMerl/asuswrt-merlin.ng#397]
Router: RT-AC66U_B1
![a](https://user-images.githubusercontent.com/3808250/71353299-e36b8880-2578-11ea-80d5-14b8111f69a7.gif)

**Comment by H3llK33p3r** [comment]
I think I already have a similiar issue when I was "not connected". In some case, I can see menus and options on the router because I have checked the "keep connection" on login. But changing settings do not work and most of the time the login page is displayed. When you try to forward the port were you already log or you had logged in just before the operation ?

**Comment by RMerl** [comment]
This feature definitely works, there is something in your particular setup interfering with the webui.  I recommend using the official support forums at SNBForums.
