### ISSUE TITLE
RT-AC86U PPPOE WAN MTU

### ISSUE THREAD

**Issue by proc999** [RMerl/asuswrt-merlin.ng#622]
Is this possible to ask ASUS to compile the bcm_enet.ko module with CONFIG_BCM_JUMBO_FRAME=y kernel option?
Otherwise the ethernet MTU is limited to 1500 even if the hardware supports 2048 (mini jumbo) MTU

**Comment by npmstart-pray** [comment]
Does your ISP support it?

**Comment by proc999** [comment]
yes, the ISP supports RFC 4638

**Comment by npmstart-pray** [comment]
The functionality you seek may already be included: It’s been a while since I tripped across jumbo frames on the router, but I do remember somewhere in the PPPoE setup on my AC86u that there are boxes to input both MTU (I went looking when I was setting up cake-QoS) as well as MRU.  Have you tried enabling jumbo frames and then adjusting MTU & MRU, all within the firmware?

**Comment by proc999** [comment]
Yes, I enabled the Jumbo Frame on the Switch Settings, and set the MTU/MRU to 1500 on the WAN settings, but the eth0 MTU remains 1500 and the PPPoE MTU is 1492
I will ask about this on the Merlin forum.

**Comment by JackMerlin** [comment]
>  I will ask about this on the Merlin forum.
Glad to see you doing this, if you have already raised a question on the Merlin forum, please close this issue, thank you.
