### ISSUE TITLE
Compile For DSL variants

### ISSUE THREAD

**Issue by dev4perf** [RMerl/asuswrt-merlin.ng#91]
Can Merlin be compiled for DSL modems?

**Comment by RMerl** [comment]
No.

**Comment by vladut123** [comment]
Why it can not be

**Comment by RMerl** [comment]
Because this repository doesn't contain the closed source components for any of the DSL models, and I have zero plan to support any of these.  Each specific model is a lot of work to support and maintain, and DSL models are simply not worth the trouble, especially since Asus does not update their source code at the same frequency as all the other models, making it impossible to keep the code base in sync.
